### PR TITLE
figured out the api with Jordan and Baylie

### PR DESCRIPTION
**Pull request by Jowest015**
creating pull request

### CODE REVIEW

**Review by Jowest015 — COMMENTED** [review]
reviewed the conflicts in app.js, don't see any problems.

**Comment by Jowest015** [comment]
Also how am I able to make a pull request from Shane's branch?

**Comment by Kavian-Spells** [comment]
Do we still need this pull request? Have we already merged?

**Comment by TaylorFurman** [comment]
This pull request should be completed, unless Shane made a change to the api I dont know aboutl

**Comment by Jowest015** [comment]
gonna let shane do the pull request if he needs it

**Pull request closed without merging**
